CREATE TABLE USERS (
  ID       BIGSERIAL    NOT NULL,
  VERSION  INTEGER               DEFAULT 0,
  EMAIL    VARCHAR(255) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  ROLE     VARCHAR(100) NOT NULL DEFAULT 'USER',
  CART     BIGINT,

  PRIMARY KEY (ID)
)