CREATE TABLE FINALIZED_ORDER (
  ID        BIGSERIAL   NOT NULL,
  VERSION   INTEGER              DEFAULT 0,
  SELL_DATE TIMESTAMPTZ        NOT NULL,
  STATE     VARCHAR(50) NOT NULL DEFAULT 'GENERAL',
  BUYER      BIGSERIAL   NOT NULL,

  PRIMARY KEY (ID)
)