CREATE TABLE USERS (
  ID       BIGINT       NOT NULL,
  VERSION  INTEGER,
  EMAIL    VARCHAR(255) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  ROLE     VARCHAR(100) NOT NULL DEFAULT 'USER',
  CART     BIGINT,

  PRIMARY KEY (ID)
)