CREATE TABLE MEDICINES_ORDER (
  ID       BIGSERIAL  NOT NULL,
  VERSION  INTEGER               DEFAULT 0,
  CART     BIGINT  NOT NULL,
  MEDICINE BIGINT  NOT NULL,
  NUMBER   INTEGER NOT NULL DEFAULT 1,

  PRIMARY KEY (ID)
)